# SPDX-License-Identifier: AGPL-3.0-or-later

use_default_settings: true

categories_as_tabs:
  general:
  images:
  videos:
  news:
  music:

general:
  instance_name: "Search4XNG"

search:
  favicon_resolver: "duckduckgo"

ui:
  default_theme: simple
  default_locale: "es"
  center_alignment: false
  theme_args:
    simple_style: dark

valkey:
  url: valkey://valkey:6379/0
