# SPDX-License-Identifier: AGPL-3.0-or-later

use_default_settings:
  engines:
    keep_only:
      - google cse
      - google cse images

general:
  instance_name: "Search4XNG"
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  favicon_resolver: "duckduckgo"
  formats:
    - html
    - json

server:
  limiter: true
  public_instance: false
  image_proxy: true
  method: "POST"

outgoing:
  request_timeout: 1.4
  max_request_timeout: 1.4

ui:
  default_theme: simple
  default_locale: "es"
  center_alignment: false
  theme_args:
    simple_style: dark

valkey:
  url: valkey://valkey:6379/0

enabled_plugins:
  - "Basic Calculator"
  - "Hash plugin"
  - "Hostnames plugin"
  - "Open Access DOI rewrite"
  - "Self Information"
  - "Tracker URL remover"
  - "Unit converter plugin"
